backend:
  name: github
  repo: gibranbuana14-sketch/my-website-
  branch: main
  base_url: https://auth.sveltia.dev

media_folder: "manda food/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Halaman Website"
    files:
      - label: "Halaman Utama"
        name: "index"
        file: "manda food/index.html"
        fields:
          - {label: "Isi HTML", name: "body", widget: "code", default_language: "html"}
